# Submission 状态机，对应契约第 18.2 节 Submission 状态迁移表。
# 完整迁移链：
#   SUBMITTED → AI_REVIEWING（enqueueAIReview）
#   AI_REVIEWING → AI_PASSED（aiReviewPass）
#   AI_REVIEWING → RETURNED（aiReviewReturn）
#   AI_REVIEWING → NEEDS_HUMAN_REVIEW（aiReviewNeedHuman / aiReviewFailedToHuman）
#   AI_PASSED/NEEDS_HUMAN_REVIEW → HUMAN_REVIEWING（claimReview）
#   HUMAN_REVIEWING → ACCEPTED（pass + SINGLE_REVIEW）
#   HUMAN_REVIEWING → FINAL_REVIEWING（pass + DOUBLE_REVIEW）
#   HUMAN_REVIEWING → RETURNED/REJECTED
#   FINAL_REVIEWING → ACCEPTED/RETURNED/REJECTED
