export type ErrorCode =
  | "SCHEMA_INVALID"
  | "SCHEMA_VERSION_IMMUTABLE"
  | "SCHEMA_DRAFT_CONFLICT"
  | "UNKNOWN_NODE_TYPE"
  | "UNKNOWN_VALIDATION_RULE"
  | "FIELD_NAME_DUPLICATED"
  | "NODE_ID_DUPLICATED"
  | "INVALID_JSON_PATH"
  | "INVALID_EXPRESSION"
  | "VALIDATION_FAILED"
  | "INVALID_STATE_TRANSITION"
  | "PERMISSION_DENIED"
  | "IDEMPOTENCY_CONFLICT"
  | "AI_REVIEW_FAILED"
  | "SCHEMA_GENERATION_FAILED"
  | "EXPORT_MAPPING_INVALID"
  | "FILE_NOT_READY"
  | "FILE_PERMISSION_DENIED"
  | "REVIEW_REASON_REQUIRED"
  | "REVISION_CONFLICT"
  | "RESOURCE_NOT_FOUND";

export interface ApiError {
  code: ErrorCode;
  message: string;
  details?: unknown;
  traceId: string;
}
