"""batch_3_review_configs_ai_review_jobs_review_results

Revision ID: 8a997b731cda
Revises: f9cddb67b8ed
Create Date: 2026-05-25 23:12:45.059042

"""
# 迁移脚本模板：由 alembic 自动填充 revision id、依赖版本和生成时间。
from alembic import op
import sqlalchemy as sa


revision = '8a997b731cda'
down_revision = 'f9cddb67b8ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_configs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('model_policy_id', sa.String(length=255), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('dimensions_json', sa.JSON(), nullable=False),
    sa.Column('thresholds_json', sa.JSON(), nullable=False),
    sa.Column('conclusion_mapping_json', sa.JSON(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', name='uq_review_configs_task_id')
    )
    op.create_table('ai_review_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('submission_id', sa.String(length=64), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('schema_version_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('prompt_snapshot_hash', sa.String(length=255), nullable=False),
    sa.Column('prompt_snapshot_ref', sa.String(length=64), nullable=True),
    sa.Column('model_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('raw_output_ref', sa.String(length=64), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['schema_version_id'], ['schema_versions.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('submission_id', 'attempt_no', name='uq_ai_review_jobs_submission_attempt')
    )
    op.create_table('review_results',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('submission_id', sa.String(length=64), nullable=False),
    sa.Column('schema_version_id', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['schema_version_id'], ['schema_versions.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_results')
    op.drop_table('ai_review_jobs')
    op.drop_table('review_configs')
    # ### end Alembic commands ###
